#!/bin/bash
VIMDIR=$HOME/.vim

function backup_file
{
    if [ -f $1 ]; then
        echo "Creating a backup file for $1"
        cp $1 $1.backup.`date +%Y-%m-%d-%s`
    else
        echo "$1 does not exist - skipping backup"
    fi
}

### .bashrc
source ./bashrc-setup

### fluxbox
source ./fluxbox-setup

### Awesome
source ./awesome-setup

### scripts
cp scripts/gopro /usr/bin
cp scripts/lswitch /usr/bin/layout-switch
cp scripts/xscreensaver-layout /usr/bin/xscreensaver-layout

### VIM setup
source ./vim-setup

### Fonts

echo "Setting up fonts directory"
if [ -d $HOME/.fonts ]; then
    echo "$HOME/.fonts directory exists"
else
    echo "$HOME/.fonts directory does not exists. Creating" 
    mkdir $HOME/.fonts
fi

echo "Downloading Monaco font"
wget -nv https://github.com/todylu/monaco.ttf/raw/master/monaco.ttf -O $HOME/.fonts/monaco.ttf

### Terminator
source ./terminator-setup
