#!/bin/bash

vim --version 1> /dev/null 2> /dev/null
if [ $? == 0 ]; then

    ###### .vimrc
    backup_file $HOME/.vimrc
    echo "Putting .vimrc file onto $HOME directory"
    cp ./configs/.vimrc $HOME/.vimrc

    echo "Creating .vim directory and subdirectories in a home folder"
    mkdir -p $VIMDIR
    mkdir -p $VIMDIR/autoload
    mkdir -p $VIMDIR/colors
    mkdir -p $VIMDIR/doc
    mkdir -p $VIMDIR/ftplugin
    mkdir -p $VIMDIR/plugin
    mkdir -p $VIMDIR/syntax

    ###### Vundle

    echo "Setting up Vundle"
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    if [ $? == 0 ]; then
        echo "Vundle has been cloned"
    else
        echo "Failed to download Vundle"
    fi

    ###### Jellybeans color scheme

    echo "Downloading jellybeans vim color scheme" 
    # http://www.vim.org/scripts/script.php?script_id=2555
    wget -nv http://www.vim.org/scripts/download_script.php?src_id=17225 -O $VIMDIR/colors/jellybeans.vim 

    ###### Airline

    echo "Downloading and installing vim-airline"
    # https://github.com/bling/vim-airline
    git clone https://github.com/bling/vim-airline.git
    cp -r vim-airline/autoload ~/.vim/
    cp -r vim-airline/doc ~/.vim/
    cp -r vim-airline/plugin ~/.vim/
    cp -r vim-airline/t ~/.vim/
    rm -rf vim-airline

    ###### cvim 

    echo "Downloading cvim plugin for C/C++ support"
    # http://www.vim.org/scripts/script.php?script_id=213
    wget -nv http://www.vim.org/scripts/download_script.php?src_id=21803 -O $VIMDIR/cvim.zip
    unzip -o -qq $VIMDIR/cvim.zip -d $VIMDIR/
    rm -rf $VIMDIR/cvim.zip

    ###### YCM

    echo "Configuring YCM"

    ###### Configuring Airline
    git clone https://github.com/powerline/fonts.git powerline-fonts
    cd powerline-fonts
    ./install.sh
    cd ..
    rm -rf powerline-fonts

else
    echo "vim is not installed"
fi
